/**
 * Flyx Desktop — Environment file read/write + first-run bootstrap.
 *
 * Port of packages/cli/src/lib/env-file.js, plus bootstrap():
 * on first launch, generate the secrets the server needs (JWT_SECRET,
 * HOST_KEY, FLYX_MASTER_TOKEN) and default to localhost-only
 * (HOSTNAME=127.0.0.1) — LAN sharing is an explicit opt-in in Settings.
 *
 * Also the desktop mirror of packages/app/src/lib/security/env-safety.ts
 * (keep the rules in sync): values may never contain CR, LF or NUL (a line
 * break smuggles extra KEY=VALUE lines into .env), and process-level keys
 * (NODE_OPTIONS, ELECTRON_*, PATH, …) are never handed to the server child —
 * a .env line NODE_OPTIONS=--import=… would otherwise be code execution on
 * the next restart.
 */

const fs = require("fs");
const { DATA_DIR, envPath } = require("./paths");
const { randomString } = require("./random");

// ── Safety rules (mirror of env-safety.ts) ──────────────────────

/** Keys that can never reach the server process from .env. */
const BLOCKED_KEY_PATTERNS = [
  /^NODE_/i, // NODE_OPTIONS, NODE_PATH, NODE_EXTRA_CA_CERTS, NODE_TLS_REJECT_UNAUTHORIZED…
  /^ELECTRON_/i,
  /^npm_/i,
  /^LD_/i,
  /^DYLD_/i,
  /^(PATH|PATHEXT|COMSPEC|SYSTEMROOT|WINDIR|TEMP|TMP|HOME|USERPROFILE|APPDATA|LOCALAPPDATA|PROGRAMDATA|SHELL)$/i,
  /^(UV_THREADPOOL_SIZE|OPENSSL_CONF|SSL_CERT_FILE|SSL_CERT_DIR)$/i,
  /^FLYX_(FFMPEG_PATH|STANDALONE_DIR|DATA_DIR|VLC_PATH|UPDATE_REPO|SERVER_HOST)$/i,
];

const ENV_KEY_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;
// eslint-disable-next-line no-control-regex
const LINE_BREAK_RE = /[\r\n\u0000]/;

function isBlockedEnvKey(key) {
  return BLOCKED_KEY_PATTERNS.some((re) => re.test(String(key)));
}

/** True if the value can be written to a KEY=VALUE line without injecting new lines. */
function isSafeEnvValue(value) {
  return !LINE_BREAK_RE.test(String(value));
}

/**
 * Keep only keys that are safe to hand to the server child's environment.
 * Returns the kept vars plus the NAMES of skipped keys (for logging — never
 * log the values, they may be secrets).
 *
 * @param {Record<string,string>} vars
 * @returns {{ env: Record<string,string>, skipped: string[] }}
 */
function filterServerEnv(vars) {
  const env = {};
  const skipped = [];
  for (const [k, v] of Object.entries(vars || {})) {
    if (!ENV_KEY_RE.test(k) || isBlockedEnvKey(k) || !isSafeEnvValue(v)) {
      skipped.push(k);
      continue;
    }
    env[k] = v;
  }
  return { env, skipped };
}

// ── Read / write ─────────────────────────────────────────────────

function ensureDataDir() {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }
}

function envExists() {
  return fs.existsSync(envPath);
}

function readEnv() {
  if (!envExists()) return {};
  const raw = fs.readFileSync(envPath, "utf-8");
  const vars = {};
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    // LF can't survive the split and edge CRs are trimmed; a mid-line CR or
    // a NUL can — drop that line so a corrupt entry never makes every later
    // writeEnv() refuse (which would crash every boot).
    if (LINE_BREAK_RE.test(trimmed)) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    vars[trimmed.slice(0, eq)] = trimmed.slice(eq + 1);
  }
  return vars;
}

function writeEnv(vars) {
  let content = "# Flyx environment — generated by flyx desktop\n\n";
  for (const [k, v] of Object.entries(vars)) {
    // A line break in a key/value would inject extra KEY=VALUE lines (and
    // last-duplicate-wins means it could override a secret) — refuse the
    // whole write rather than persist a smuggled line.
    if (LINE_BREAK_RE.test(k) || !isSafeEnvValue(v)) {
      throw new Error(`Refusing to write .env: ${JSON.stringify(k)} contains a line break`);
    }
    content += `${k}=${v}\n`;
  }
  ensureDataDir();
  // Atomic write: temp file (created 0600 so secrets are never briefly
  // world-readable) + rename.
  const tmp = envPath + ".tmp";
  fs.writeFileSync(tmp, content, { encoding: "utf-8", mode: 0o600 });
  try { fs.chmodSync(tmp, 0o600); } catch {}
  fs.renameSync(tmp, envPath);
}

function updateEnv(key, value) {
  const k = String(key);
  const v = String(value);
  if (!ENV_KEY_RE.test(k)) throw new Error(`Invalid env key: ${k}`);
  if (!isSafeEnvValue(v)) throw new Error(`Env value for ${k} contains a line break`);
  const vars = readEnv();
  vars[k] = v;
  writeEnv(vars);
}

/**
 * First-run bootstrap. Never overwrites an existing configuration.
 *
 * Generates the secrets the server needs (the web setup wizard only
 * collects TMDB key + account + network mode), defaults to localhost-only,
 * and lets the wizard fill in the rest later (setup/save merges).
 *
 * @returns {{firstRun: boolean}}
 */
function bootstrap() {
  if (envExists()) return { firstRun: false };

  writeEnv({
    JWT_SECRET: randomString(64),
    HOST_KEY: randomString(24),
    FLYX_MASTER_TOKEN: randomString(64),
    // Localhost-only by default; LAN sharing is an explicit opt-in
    // (Settings → Network writes HOSTNAME=0.0.0.0). Existing installs keep
    // whatever their .env says — bootstrap never rewrites it.
    HOSTNAME: "127.0.0.1",
    FLYX_DESKTOP: "true",
    PORT: "3891",
  });
  return { firstRun: true };
}

/**
 * Migration: data dirs created before the master token existed get one.
 * The server only honors FLYX_MASTER_TOKEN when it's present, so without
 * this an upgraded install would silently lose desktop auto-login.
 *
 * @returns {string} the master token (existing or freshly generated)
 */
function ensureMasterToken() {
  const vars = readEnv();
  if (!vars.FLYX_MASTER_TOKEN) {
    vars.FLYX_MASTER_TOKEN = randomString(64);
    writeEnv(vars);
  }
  return vars.FLYX_MASTER_TOKEN;
}

/**
 * Migration: heal a .env that lost JWT_SECRET/HOST_KEY (older save routes
 * rewrote the file wholesale). These MUST exist before the server starts:
 * the Next edge runtime snapshots process.env at boot and never sees
 * in-process mutations, so a secret generated later (by setup/save) would
 * split the token signer (Node runtime, live env) from the verifier (edge
 * middleware, boot snapshot) and send the master into an endless
 * auto-login redirect loop after finishing setup.
 *
 * Called before the server is first spawned and before the env watcher is
 * armed, so the heal itself never triggers a restart.
 */
function ensureSecrets() {
  const vars = readEnv();
  let changed = false;
  if (!vars.JWT_SECRET) {
    vars.JWT_SECRET = randomString(64);
    changed = true;
  }
  if (!vars.HOST_KEY) {
    vars.HOST_KEY = randomString(24);
    changed = true;
  }
  if (changed) writeEnv(vars);
}

module.exports = {
  envExists,
  readEnv,
  writeEnv,
  updateEnv,
  ensureDataDir,
  bootstrap,
  ensureMasterToken,
  ensureSecrets,
  isBlockedEnvKey,
  isSafeEnvValue,
  filterServerEnv,
  ENV_KEY_RE,
};
