/**
 * Flyx Desktop — Environment file read/write + first-run bootstrap.
 *
 * Port of packages/cli/src/lib/env-file.js, plus bootstrap():
 * on first launch, generate the secrets the server needs (JWT_SECRET,
 * HOST_KEY, FLYX_MASTER_TOKEN) and default to LAN sharing
 * (HOSTNAME=0.0.0.0).
 */

const fs = require("fs");
const { DATA_DIR, envPath } = require("./paths");
const { randomString } = require("./random");

function ensureDataDir() {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }
}

function envExists() {
  return fs.existsSync(envPath);
}

function readEnv() {
  if (!envExists()) return {};
  const raw = fs.readFileSync(envPath, "utf-8");
  const vars = {};
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    vars[trimmed.slice(0, eq)] = trimmed.slice(eq + 1);
  }
  return vars;
}

function writeEnv(vars) {
  ensureDataDir();
  let content = "# Flyx environment — generated by flyx desktop\n\n";
  for (const [k, v] of Object.entries(vars)) {
    content += `${k}=${v}\n`;
  }
  // Atomic write: temp file + rename
  const tmp = envPath + ".tmp";
  fs.writeFileSync(tmp, content, "utf-8");
  try { fs.chmodSync(tmp, 0o600); } catch {}
  fs.renameSync(tmp, envPath);
}

function updateEnv(key, value) {
  const vars = readEnv();
  vars[key] = String(value);
  writeEnv(vars);
}

/**
 * First-run bootstrap. Never overwrites an existing configuration.
 *
 * Generates the secrets the server needs (the web setup wizard only
 * collects TMDB key + account + network mode), defaults to LAN sharing,
 * and lets the wizard fill in the rest later (setup/save merges).
 *
 * @returns {{firstRun: boolean}}
 */
function bootstrap() {
  if (envExists()) return { firstRun: false };

  writeEnv({
    JWT_SECRET: randomString(64),
    HOST_KEY: randomString(24),
    FLYX_MASTER_TOKEN: randomString(64),
    HOSTNAME: "0.0.0.0", // LAN sharing on by default
    FLYX_DESKTOP: "true",
    PORT: "3891",
  });
  return { firstRun: true };
}

/**
 * Migration: data dirs created before the master token existed get one.
 * The server only honors FLYX_MASTER_TOKEN when it's present, so without
 * this an upgraded install would silently lose desktop auto-login.
 *
 * @returns {string} the master token (existing or freshly generated)
 */
function ensureMasterToken() {
  const vars = readEnv();
  if (!vars.FLYX_MASTER_TOKEN) {
    vars.FLYX_MASTER_TOKEN = randomString(64);
    writeEnv(vars);
  }
  return vars.FLYX_MASTER_TOKEN;
}

/**
 * Migration: heal a .env that lost JWT_SECRET/HOST_KEY (older save routes
 * rewrote the file wholesale). These MUST exist before the server starts:
 * the Next edge runtime snapshots process.env at boot and never sees
 * in-process mutations, so a secret generated later (by setup/save) would
 * split the token signer (Node runtime, live env) from the verifier (edge
 * middleware, boot snapshot) and send the master into an endless
 * auto-login redirect loop after finishing setup.
 *
 * Called before the server is first spawned and before the env watcher is
 * armed, so the heal itself never triggers a restart.
 */
function ensureSecrets() {
  const vars = readEnv();
  let changed = false;
  if (!vars.JWT_SECRET) {
    vars.JWT_SECRET = randomString(64);
    changed = true;
  }
  if (!vars.HOST_KEY) {
    vars.HOST_KEY = randomString(24);
    changed = true;
  }
  if (changed) writeEnv(vars);
}

module.exports = { envExists, readEnv, writeEnv, updateEnv, ensureDataDir, bootstrap, ensureMasterToken, ensureSecrets };
