/**
 * Flyx CLI — Environment file read/write.
 *
 * Port of packages/desktop/main/env-store.js
 */

const fs = require("fs");
const path = require("path");
const { DATA_DIR, envPath } = require("./paths");

function ensureDataDir() {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }
}

function envExists() {
  return fs.existsSync(envPath);
}

function readEnv() {
  if (!envExists()) return {};
  const raw = fs.readFileSync(envPath, "utf-8");
  const vars = {};
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    vars[trimmed.slice(0, eq)] = trimmed.slice(eq + 1);
  }
  return vars;
}

function writeEnv(vars) {
  ensureDataDir();
  let content = "# Flyx environment — generated by flyx setup\n\n";
  for (const [k, v] of Object.entries(vars)) {
    content += `${k}=${v}\n`;
  }
  // Atomic write: temp file + rename
  const tmp = envPath + ".tmp";
  fs.writeFileSync(tmp, content, "utf-8");
  try { fs.chmodSync(tmp, 0o600); } catch {}
  fs.renameSync(tmp, envPath);
}

function updateEnv(key, value) {
  const vars = readEnv();
  vars[key] = String(value);
  writeEnv(vars);
}

module.exports = { envExists, readEnv, writeEnv, updateEnv, ensureDataDir };
