/**
 * Flyx CLI — Environment file read/write.
 *
 * Port of packages/desktop/main/env-store.js
 *
 * .env safety rules mirror packages/app/src/lib/security/env-safety.ts
 * (keep in sync): a value containing CR/LF/NUL could smuggle extra KEY=VALUE
 * lines into the file, and every key in .env is handed to the server
 * process's environment — keys that steer how Node starts (NODE_OPTIONS…)
 * or where Flyx loads binaries from are code execution, so they are refused.
 */

const fs = require("fs");
const { DATA_DIR, envPath } = require("./paths");

const BLOCKED_KEY_PATTERNS = [
  /^NODE_/i, // NODE_OPTIONS, NODE_PATH, NODE_EXTRA_CA_CERTS, NODE_TLS_REJECT_UNAUTHORIZED…
  /^ELECTRON_/i,
  /^npm_/i,
  /^LD_/i,
  /^DYLD_/i,
  /^(PATH|PATHEXT|COMSPEC|SYSTEMROOT|WINDIR|TEMP|TMP|HOME|USERPROFILE|APPDATA|LOCALAPPDATA|PROGRAMDATA|SHELL)$/i,
  /^(UV_THREADPOOL_SIZE|OPENSSL_CONF|SSL_CERT_FILE|SSL_CERT_DIR)$/i,
  /^FLYX_(FFMPEG_PATH|STANDALONE_DIR|DATA_DIR|VLC_PATH|UPDATE_REPO|SERVER_HOST)$/i,
];

const ENV_KEY_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

function isBlockedEnvKey(key) {
  return BLOCKED_KEY_PATTERNS.some((re) => re.test(key));
}

/** True if the value can be written to a KEY=VALUE line without injecting new lines. */
function isSafeEnvValue(value) {
  // eslint-disable-next-line no-control-regex
  return !/[\r\n\u0000]/.test(String(value));
}

/** Throws if key/value must not be written to .env. */
function assertSafeEnvEntry(key, value) {
  if (!ENV_KEY_RE.test(key)) throw new Error(`Invalid env key: ${key}`);
  if (isBlockedEnvKey(key)) throw new Error(`Env key ${key} cannot be set`);
  if (!isSafeEnvValue(value)) throw new Error(`Env value for ${key} contains a line break`);
}

/** Drop keys that must never reach a child process environment. */
function filterBlockedKeys(vars) {
  const out = {};
  for (const [k, v] of Object.entries(vars || {})) {
    if (!ENV_KEY_RE.test(k) || isBlockedEnvKey(k)) continue;
    out[k] = v;
  }
  return out;
}

function ensureDataDir() {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true, mode: 0o700 });
  }
}

function envExists() {
  return fs.existsSync(envPath);
}

function parseEnv(raw) {
  const vars = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    vars[trimmed.slice(0, eq)] = trimmed.slice(eq + 1);
  }
  return vars;
}

function readEnv() {
  if (!envExists()) return {};
  return parseEnv(fs.readFileSync(envPath, "utf-8"));
}

/**
 * Write the full .env. Every entry is validated first (nothing is written if
 * any entry is unsafe). Blocked keys that are already present in the file
 * (e.g. hand-edited) are dropped rather than preserved.
 */
function writeEnv(vars) {
  const entries = [];
  for (const [k, v] of Object.entries(vars)) {
    const value = v === undefined || v === null ? "" : String(v);
    if (isBlockedEnvKey(k)) continue; // never persist a blocked key
    assertSafeEnvEntry(k, value);
    entries.push([k, value]);
  }
  ensureDataDir();
  let content = "# Flyx environment — generated by flyx setup\n\n";
  for (const [k, v] of entries) {
    content += `${k}=${v}\n`;
  }
  // Atomic write: temp file (created 0600) + rename
  const tmp = envPath + ".tmp";
  fs.writeFileSync(tmp, content, { encoding: "utf-8", mode: 0o600 });
  try { fs.chmodSync(tmp, 0o600); } catch {}
  fs.renameSync(tmp, envPath);
}

/** Set a single key. Throws on a blocked key or unsafe value. */
function updateEnv(key, value) {
  assertSafeEnvEntry(key, String(value));
  const vars = readEnv();
  vars[key] = String(value);
  writeEnv(vars);
}

module.exports = {
  envExists,
  readEnv,
  parseEnv,
  writeEnv,
  updateEnv,
  ensureDataDir,
  isBlockedEnvKey,
  isSafeEnvValue,
  assertSafeEnvEntry,
  filterBlockedKeys,
};
